import { NextResponse } from 'next/server';

// Language code mapping for Sarvam AI
const SARVAM_LANGUAGE_MAP = {
  'hi': 'hi-IN',
  'en': 'en-IN',
  'ta': 'ta-IN',
  'te': 'te-IN',
  'kn': 'kn-IN',
  'mr': 'mr-IN',
  'bn': 'bn-IN',
  'gu': 'gu-IN',
  'ml': 'ml-IN',
  'pa': 'pa-IN',
  'od': 'od-IN',
};

export async function POST(request) {
  try {
    const body = await request.json();
    const { text, language = 'hi', speaker = 'priya', pace = 1.0 } = body;

    if (!text || text.trim().length === 0) {
      return NextResponse.json({ success: false, error: 'Text is required' }, { status: 400 });
    }

    const sarvamKey = process.env.SARVAM_API_KEY;

    if (!sarvamKey) {
      return NextResponse.json({
        success: false,
        error: 'SARVAM_API_KEY not configured in .env.local',
        fallback: true,
      }, { status: 400 });
    }

    // Clean text for TTS (remove emojis and special formatting)
    const cleanText = text
      .replace(/🤖 AI Voice:|👤 Customer:|🤖|👤/g, '')
      .replace(/[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F1E0}-\u{1F1FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu, '')
      .trim()
      .slice(0, 2400); // Sarvam limit is 2500 chars

    const languageCode = SARVAM_LANGUAGE_MAP[language] || 'hi-IN';

    const sarvamRes = await fetch('https://api.sarvam.ai/text-to-speech', {
      method: 'POST',
      headers: {
        'api-subscription-key': sarvamKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        text: cleanText,
        language_code: languageCode,
        speaker: speaker,
        model: 'bulbul:v3',
        pace: pace,
      }),
    });

    if (!sarvamRes.ok) {
      const errorText = await sarvamRes.text();
      console.error('Sarvam AI error:', sarvamRes.status, errorText);
      return NextResponse.json({
        success: false,
        error: `Sarvam API error: ${sarvamRes.status}`,
        fallback: true,
      }, { status: 500 });
    }

    const sarvamData = await sarvamRes.json();

    if (!sarvamData.audios || sarvamData.audios.length === 0) {
      return NextResponse.json({
        success: false,
        error: 'No audio generated by Sarvam AI',
        fallback: true,
      }, { status: 500 });
    }

    return NextResponse.json({
      success: true,
      audioBase64: sarvamData.audios[0],
      language: languageCode,
      speaker: speaker,
      model: 'bulbul:v3',
    });
  } catch (error) {
    console.error('Voice speak error:', error);
    return NextResponse.json(
      { success: false, error: error.message || 'Voice generation failed', fallback: true },
      { status: 500 }
    );
  }
}
